PatientPaI/backend

- src/main/java/com/patientpal/backend/member/domain/Gender.java
- src/main/java/com/patientpal/backend/member/domain/Member.java
- src/main/java/com/patientpal/backend/member/domain/Provider.java
- src/main/java/com/patientpal/backend/member/domain/Role.java
- 간단한 Member 엔티티와 연관된 Enum들을 추가했습니다.
- 멤버 엔티티는 아직 완성된 것이 아니며 향후 수정될 수 있습니다.
- PR 시 AI가 제대로 리뷰를 다는지 확인하고 싶어서 임의로 브랜치를 만들게 되었습니다.
> [feat] Member 엔티티를 추가한다

- .github/ISSUE_TEMPLATE/new_feature.yml
- .github/ISSUE_TEMPLATE/refactor.yml
- '기능 추가', '리팩토링' 이슈 등록 시 프로젝트에 자동으로 등록할 수 있게끔 수정했습니다.
> Feat: 기능 추가, 리팩터링 이슈 등록 시 프로젝트를 자동으로 할당한다.

- .github/workflows/auto_assign_action.yml
- 권한 문제 때문에 접근할 수 없어서 액션이 제대로 동작하지 않는 부분을 수정했습니다.
> Fix: 권한 문제로 인해 Auto assign action이 제대로 동작하지 않는 것을 수정함

- src/main/java/com/patientpal/backend/noticecommunity/controller/PostController.java
- src/main/java/com/patientpal/backend/shared/config/JpaAuditingConfig.java
- src/main/resources/application-local.yaml
- JPAauditing 어노테이션이 누락되어 추가하였습니다
- Application 파일에 추가하여 관리 / config 파일을 따로 만들어 관리
두 선택지 중 메인 코드는 최대한 건들지 않는 것이 좋다고 생각하여 shared 폴더를 따로 만들어 공유하였습니다.
- https://lahezy.tistory.com/114
- https://webcoding-start.tistory.com/53
> Fix: BaseTimeEntity 를 위한 JPA auditing config 추가 

- src/main/java/com/patientpal/backend/config/SecurityConfig.java
- src/main/java/com/patientpal/backend/matching/application/MatchService.java
- src/main/java/com/patientpal/backend/matching/application/MatchServiceImpl.java
- src/main/java/com/patientpal/backend/matching/domain/Match.java
- src/main/java/com/patientpal/backend/matching/domain/MatchRepository.java
- src/main/java/com/patientpal/backend/matching/domain/MatchStatus.java
- src/main/java/com/patientpal/backend/matching/domain/ReadStatus.java
- src/main/java/com/patientpal/backend/matching/dto/response/CreateMatchResponse.java
- src/main/java/com/patientpal/backend/matching/dto/response/MatchResponse.java
- src/main/java/com/patientpal/backend/matching/presentation/MatchController.java
- src/main/java/com/patientpal/backend/member/domain/CaregiverRepository.java
- src/main/java/com/patientpal/backend/member/domain/PatientRepository.java
- @AuthenticationPrincipal Member currentMember 이부분 NPE 발생
- 디버깅 부탁드립니다
> Feat: NPE 문제 디버깅

- src/main/java/com/patientpal/backend/post/domain/Post.java
- src/main/java/com/patientpal/backend/post/dto/PostCreateRequest.java
- src/main/java/com/patientpal/backend/post/dto/PostCreateResponse.java
- src/main/java/com/patientpal/backend/post/dto/PostListResponse.java
- src/main/java/com/patientpal/backend/post/dto/PostResponse.java
- src/main/java/com/patientpal/backend/post/dto/PostUpdateRequest.java
- Post Entity @RequiredArgsConstructor 제거, @NoArgsConstructor(access = AccessLevel.PROTECTED) 추가
- Post 내부 코드 라인 재조정
- 모든 DTO @NoArgsConstructor(access = AccessLevel.PRIVATE), @Getter, 전체 생성자는 추후 final 키워드 추가 할 가능성으로 인해 직접 생성
- 다시 한 번 확인 부탁드립니다.
> Refactor: Post 관련 DTO 수정

- .github/workflows/build-and-deploy.yml
main에 변경사항이 발생하면 빌드 후 도커 레지스트리에 이미지를 배포하고 컨테이너를 실행합니다.
- 서비스가 얼추 완성되면 무중단 배포를 위해서 좀 더 수정을 해보던가 여러가지 부분을 고려해볼 수 있을 것 같습니다.
- close #42
> Ci: 변경사항 발생 시 빌드 후 배포하는 자동화 파이프라인 구성

- .github/workflows/build-and-deploy.yml
- Dockerfile
Dockerfile가 프로젝트 루트 경로에 존재하지 않아 잡이 실패하는 것 같아서 다시 올립니다.
- #43
> Ci: Dockerfile을 Alpine 기반 이미지로 변경

- src/main/java/com/patientpal/backend/common/advice/RestApiExceptionHandler.java
- src/main/java/com/patientpal/backend/config/SwaggerConfig.java
- src/main/resources/application.yml
- application 설정 정보 수정 (local -> prod)
- swagger 운영 서버 미동작 수정 후 재배포
- 보안 정보 유출 여부 더블 체크 부탁드립니다.
> Fix: swagger 관련 운영서버 미작동 이슈 수정, 공통 예외 핸들러 베이스 패키지 지정

- src/main/java/com/patientpal/backend/member/service/MemberService.java
- src/main/java/com/patientpal/backend/post/controller/NoticeController.java
- src/main/java/com/patientpal/backend/post/service/PostService.java
- Patch, Delete 요청에 Role 이 ADMIN 인지 검사하는 코드 추가하였습니다.
> Fix: 공지사항 변경 및 제거 시 올바른 접근 권한을 가지고 있는지 확인하도록 함

- src/main/java/com/patientpal/backend/config/InterceptorConfig.java
- src/main/java/com/patientpal/backend/member/domain/Role.java
- src/main/java/com/patientpal/backend/post/controller/NoticeController.java
- src/main/java/com/patientpal/backend/post/libs/RoleInterceptor.java
- src/main/java/com/patientpal/backend/post/libs/RoleType.java
- RoleType 커스텀 어노테이션을 만들었습니다.
- RoleType을 검사하는 인터셉터를 만들었습니다.
- InterceptorConfig를 만들었습니다.
- ~Role 에 PATIENT타입을 추가하였습니다.~
- #38
> Feat: Roletype custom annotation 구현 후 적용

- src/main/java/com/patientpal/backend/common/controller/PingController.java
- src/main/java/com/patientpal/backend/config/config/JpaAuditingConfig.java
shared 패키지와 common 패키지가 성격이 유사한 것 같아서 혼란을 피하기 위해 서로 병합했습니다.
- close #56
> Rename: 성격이 비슷한 두 패키지를 병합함

- src/main/resources/application.yml
- `ddl-auto`를 `validate`에서 `none`으로 변경
- 팀원들은 기본적으로 `local`에서 작업하므로 기본 활성 프로필을 `prod`가 아닌 `local`로 변경
- 운영 서버 환경에서의 테스트가 필요한 경우에는 `application.yml`를 수정하는 것보다는 `Edit Configurations`에서 `Active profiles`를 이용해보는 것도 괜찮을 것 같아요! 🐱 
- close #58
> Config: 운영 환경에서 스키마를 검증하지 않도록 변경함

- .github/workflows/build-and-deploy.yml
- Dockerfile
- Docker run 명령에 PROD_PROFILE 환경 변수 추가
- Dockerfile에서 prod 프로필을 사용하도록 ENTRYPOINT 수정
- close #60
> Fix: 운영 서버에서 prod 프로필을 사용하도록 Docker 설정 수정

- src/main/java/com/patientpal/backend/auth/domain/RefreshToken.java
- src/main/java/com/patientpal/backend/caregiver/domain/Caregiver.java
- src/main/java/com/patientpal/backend/matching/domain/Match.java
- src/main/java/com/patientpal/backend/member/domain/Member.java
- src/main/java/com/patientpal/backend/patient/domain/Patient.java
- src/main/java/com/patientpal/backend/post/domain/Post.java
- 테이블 명을 복수형으로 통일합니다.
- close #73
> Refactor: 테이블 명을 복수형으로 통일함

- .github/auto_assign_config.yml
- .github/custom_google_checks.xml
- 한글 테스트 메서드 명으로 인해 코멘트가 도배가 되는 부분이 있어서 네이밍 컨벤션을 급하게 완화합니다.
- 작동하지 않는 리뷰어 자동 등록 액션을 수정합니다.
- 편의를 위해 checkstyle 메시지를 한국어로 번역합니다.
- 도배가 좀 심해서 빠르게 머지하도록 하겠습니다.
> Fix: 한글 테스트 메서드 명을 위해 메서드 네이밍 컨벤션을 완화함

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/deployment.yml
- .github/ISSUE_TEMPLATE/documentation.yml
- .github/ISSUE_TEMPLATE/environment.yml
- .github/ISSUE_TEMPLATE/meeting.yml
- .github/ISSUE_TEMPLATE/new_feature.yml
- .github/ISSUE_TEMPLATE/refactor.yml
- .github/ISSUE_TEMPLATE/testing.yml
- '배포', '테스트', '환경설정', '문서화' 카테고리가 새로 추가되었습니다.
- 이슈 폼에서 중복되는 부분은 제거하여 간소화 했습니다(예: 리팩터링 설명과 리팩터링 목표는 중복되는 부분이 있음).
- 버그 리포트에서 '실제 동작'과 '예상 동작'은 참고가 되는 귀중한 정보이기에 필수 필드로 설정했습니다.
- close #79
> Doc: 편의를 위해 이슈 카테고리를 세분화함

- src/main/java/com/patientpal/backend/common/advice/RestApiExceptionHandler.java
- src/main/java/com/patientpal/backend/webhook/dto/DiscordMessage.java
- src/main/java/com/patientpal/backend/webhook/service/DiscordWebhookService.java
- src/main/resources/application.yml
- 운영 서버에서 비정상 예외 발생 시 웹훅을 통해 디스코드 채널로 전달하도록 합니다.
- 이 기능은 추후에 모니터링 수단이 마련되면 서버의 부담을 줄이기 위해서 제거될 수 있습니다.
- Closes #81 
- [[AvAb] Spring + Discord Webhook으로 에러 상황 알림 받기](https://velog.io/@eomgerm/AvAb-Spring-Discord-Webhook%EC%9C%BC%EB%A1%9C-%EC%97%90%EB%9F%AC-%EC%83%81%ED%99%A9-%EC%95%8C%EB%A6%BC-%EB%B0%9B%EA%B8%B0)
> Feat: 운영 서버에서 비정상 예외 발생 시 웹훅을 통해 디스코드 채널로 전달하도록 함

- src/test/java/com/patientpal/backend/caregiver/service/CaregiverServiceTest.java
- src/test/java/com/patientpal/backend/patient/service/PatientServiceTest.java
- 삭제 기능 구현 후 기존 테스트 실패 해결
- 삭제 기능 구현 후 계획했던 삭제 중 진행중인 매칭 존재 시 예외 발생 테스트 진행
- Fixes #85
> Fix: 삭제 관련 테스트 실패 문제 해결

- src/main/resources/application.yml
- 보안 강화를 위해 Jasypt 암호화 비밀키를 변경하였습니다. (키 값 별도 공지)
- 추가적인 보안 유출 가능성 확인 바랍니다
> Config: Jasypt 암호화 키 변경

- src/main/java/com/patientpal/backend/matching/controller/MatchController.java
- src/main/java/com/patientpal/backend/matching/service/MatchService.java
- src/main/java/com/patientpal/backend/matching/service/MatchServiceImpl.java
- src/main/java/com/patientpal/backend/member/domain/Member.java
- src/test/java/com/patientpal/backend/fixtures/caregiver/CaregiverFixture.java
- src/test/java/com/patientpal/backend/fixtures/match/MatchFixture.java
- src/test/java/com/patientpal/backend/fixtures/patient/PatientFixture.java
- src/test/java/com/patientpal/backend/matching/controller/MatchControllerTest.java
- src/test/java/com/patientpal/backend/matching/service/CaregiverMatchServiceTest.java
- src/test/java/com/patientpal/backend/matching/service/PatientMatchServiceTest.java
- Match 관련 중복 코드 리팩토링
- MatchController Endpoint 테스트 코드 작성
- MatchService 테스트 Patient/Caregiver 나눠서 테스트 코드 작성
- Closes #99
> Feat: 매칭 서비스 테스트 추가

- src/main/java/com/patientpal/backend/config/SecurityConfig.java
- CORS 문제를 해결하기 위해서 `CorsFilter`를 추가하고 설정으로 지정합니다.
- close #103
> Config: CorsFilter 추가

- src/main/java/com/patientpal/backend/post/controller/BoardController.java
- src/main/java/com/patientpal/backend/post/controller/NoticeController.java
- src/main/java/com/patientpal/backend/post/service/PostService.java
- 회원게시판 전용 엔드포인트를 추가했습니다.
- 회원 전용 게시판을 비회원도 볼 수 있게 할 것인지 논의 필요할 것 같습니다.
- #65
> Feat: 회원게시판 관련 API 엔드포인트 추가

- src/main/java/com/patientpal/backend/caregiver/service/CaregiverService.java
- src/main/java/com/patientpal/backend/member/domain/Member.java
- src/main/java/com/patientpal/backend/patient/service/PatientService.java
- src/test/java/com/patientpal/backend/caregiver/controller/CaregiverControllerV1Test.java
- src/test/java/com/patientpal/backend/caregiver/service/CaregiverServiceTest.java
- src/test/java/com/patientpal/backend/fixtures/auth/SignUpRequestFixture.java
- src/test/java/com/patientpal/backend/fixtures/caregiver/CaregiverFixture.java
- src/test/java/com/patientpal/backend/fixtures/match/MatchFixture.java
- src/test/java/com/patientpal/backend/fixtures/member/MemberFixture.java
- src/test/java/com/patientpal/backend/fixtures/patient/PatientFixture.java
- src/test/java/com/patientpal/backend/matching/controller/MatchControllerTest.java
- src/test/java/com/patientpal/backend/matching/service/CaregiverMatchServiceTest.java
- src/test/java/com/patientpal/backend/matching/service/PatientMatchServiceTest.java
- src/test/java/com/patientpal/backend/patient/controller/PatientControllerV1Test.java
- src/test/java/com/patientpal/backend/patient/service/PatientServiceTest.java
- 환자 프로필 관련 서비스, 컨트롤러 테스트 수정
- 간병인 프로필 관련 서비스, 컨트롤러 테스트 수정
- 관련 Fixture 수정
- 불필요한 fixture 제거 default로 통일.
- Member 테이블에 isCompleteProfile 필드 추가 (세부 프로필 등록 시 true, 이후 매칭 리스트에 등록 가능)
- Closes #113
> Test: 테이블 구조 변경에 따라 기존 테스트 수정

- .github/workflows/build_and_deploy.yml
- github actions를 이용한 통합과 배포 자동화
- #120
> Deployment: DOCKER를 사용해 CI/CD 진행

- .github/workflows/gradle.yml
> Deployment: CI/CD

- .github/workflows/build.yml
- build 최종 단계 시 prod 프로필 설정 추가
> Deployment: docker build시 profile 지정 추가

- .github/workflows/build.yml
> Deployment: docker build 스크립트 수정

- .github/workflows/CICD.yml
- docker 실행 명령어에 소셜 로그인 환경 변수 추가
> Deployment: docker 실행 명령어에 소셜 로그인 환경 변수 추가

- src/main/java/com/patientpal/backend/post/dto/PostCreateResponse.java
- 단순 DTO 리팩토링 입니다
- Post엔티티의 responseDTO에서 update, created DTO 의 필드명을 통일하였습니다.
- #138
> Refactor: Post엔티티 update, created Date 필드명 변경

- .github/workflows/CICD.yml
- docker-compose.yml
> Feat: docker-compose.yml 추가

- src/main/java/com/patientpal/backend/member/service/MemberService.java
- MemberService에 admin role 가입 절차 추가
- #142
> Bug: ADMIN 으로 가입 실패 에러 수정

- src/main/java/com/patientpal/backend/common/controller/PingController.java
> Fix: ec2 target group config

- src/main/java/com/patientpal/backend/common/controller/PingController.java
- src/main/java/com/patientpal/backend/config/SwaggerConfig.java
- src/main/resources/application.yml
> Config: add https

- src/main/java/com/patientpal/backend/common/controller/PingController.java
- src/main/java/com/patientpal/backend/config/SwaggerConfig.java
- src/main/resources/application.yml
- https 미완성으로 인해 스웨거에 기존 http도 같이 열어놓겠습니다.
> Fix: http, https 스웨거 동시 허용

- src/main/java/com/patientpal/backend/common/TimeTrace.java
- src/main/java/com/patientpal/backend/common/logger/LogAspect.java
- src/main/java/com/patientpal/backend/common/logger/MDCFilter.java
- src/main/java/com/patientpal/backend/patient/controller/PatientControllerV1.java
- src/main/resources/logback.xml
- 사용자별 구분을 위한 로그 추적 - MDC 
- 요청 별 호출 시간 측정 어노테이션 - @TimeTrace
> Feat: Log, Time Trace

- src/main/java/com/patientpal/backend/config/SecurityConfig.java
> Config: CORS Security 설정

- src/main/java/com/patientpal/backend/config/SwaggerConfig.java
- src/main/resources/application.yml
> Deployment: https로 변경

- build.gradle
- src/main/java/com/patientpal/backend/caregiver/controller/CaregiverControllerV1.java
- src/main/java/com/patientpal/backend/caregiver/service/CaregiverSearchService.java
- src/main/java/com/patientpal/backend/caregiver/service/CaregiverService.java
- src/main/java/com/patientpal/backend/config/MetricConfig.java
- src/main/java/com/patientpal/backend/matching/service/MatchServiceImpl.java
- src/main/java/com/patientpal/backend/matching/service/PdfService.java
- src/main/java/com/patientpal/backend/patient/controller/PatientControllerV1.java
- src/main/java/com/patientpal/backend/patient/service/PatientSearchService.java
- src/main/java/com/patientpal/backend/patient/service/PatientService.java
- src/main/resources/application.yml
- search 클래스 분리
- prometheus, grafana 설정 정보 추가
- #162
> Feat: add monitoring

- src/main/java/com/patientpal/backend/caregiver/dto/response/CaregiverRankingResponse.java
- src/main/java/com/patientpal/backend/caregiver/repository/CaregiverRepository.java
- src/main/java/com/patientpal/backend/common/exception/ErrorCode.java
- src/main/java/com/patientpal/backend/review/controller/ReviewController.java
- src/main/java/com/patientpal/backend/review/domain/Review.java
- src/main/java/com/patientpal/backend/review/dto/ReviewRequest.java
- src/main/java/com/patientpal/backend/review/dto/ReviewResponse.java
- src/main/java/com/patientpal/backend/review/repository/ReviewRepository.java
- src/main/java/com/patientpal/backend/review/service/ReviewService.java
- src/test/java/com/patientpal/backend/review/controller/ReviewControllerTest.java
- src/test/java/com/patientpal/backend/review/service/ReviewServiceTest.java
- 리뷰를 생성, 조회, 수정, 삭제가 기능구현
- 지역별 랭킹을 위해 응답으로 CaregiverRankingResponse 생성
- 평점 기능을 stream으로 구현 
- 리뷰 기능 및 평점 서비스 와 컨트롤러 테스트 구현
> Feat: 리뷰 기능 및 랭킹

- src/main/java/com/patientpal/backend/member/service/MemberService.java
- src/main/java/com/patientpal/backend/post/domain/Post.java
- post의 컬럼 타입을 TEXT로 변경 
- #169
> Feat: content column type 변경

- src/main/java/com/patientpal/backend/post/controller/BoardController.java
- src/main/java/com/patientpal/backend/post/controller/NoticeController.java
- src/main/java/com/patientpal/backend/post/domain/Post.java
- src/main/java/com/patientpal/backend/post/dto/PostCreateResponse.java
- src/main/java/com/patientpal/backend/post/dto/PostListResponse.java
- src/main/java/com/patientpal/backend/post/dto/PostResponse.java
- src/main/java/com/patientpal/backend/post/repository/PostRepository.java
- src/main/java/com/patientpal/backend/post/service/PostService.java
- 게시판에 조회수 기능을 추가하였습니다
- Closes #111
> Feat: 게시판 조회수 기능 추가

- .github/workflows/CICD.yml
- docker-compose.yml
- src/main/java/com/patientpal/backend/member/controller/MemberController.java
> Deployment: add blue/green deployment

- src/main/java/com/patientpal/backend/auth/controller/AuthenticationApiV1Controller.java
- src/main/java/com/patientpal/backend/config/SecurityConfig.java
- src/main/java/com/patientpal/backend/security/jwt/JwtTokenProvider.java
- src/test/java/com/patientpal/backend/auth/controller/AuthenticationApiV1ControllerTest.java
- 로그아웃 시 로그인 페이지 이동 x
- 로그아웃 시 리프레쉬 토큰 만료
> [fix] 로그아웃 시 로그인 페이지 이동 안하기 와 리프래쉬 토큰 만료 

- src/main/java/com/patientpal/backend/chat/domain/Chat.java
- src/main/java/com/patientpal/backend/chat/domain/Message.java
- chats, messages 이름을 소문자로 변경하였습니다
> Refactor: 테이블 이름 수정

- src/main/java/com/patientpal/backend/config/WebSocketConfig.java
- Websocket config 에 CORS 주소를 추가했습니다.
> Feat: Websocket config CORS 주소 추가

- src/main/java/com/patientpal/backend/common/BaseTimeEntity.java
- src/main/java/com/patientpal/backend/member/domain/Member.java
- src/main/java/com/patientpal/backend/notification/domain/Notification.java
- 간병원하는시간 공통 시간 entity에서 제거
- 알림 엔티티 테이블명 소문자 + 복수형으로 변경
> Fix: Delete wantCareDate in common Entity

- src/main/java/com/patientpal/backend/chat/dto/ChatCreateRequest.java
> Fix: Add @NoArgsContructor in ChatCreateRequest

- src/main/java/com/patientpal/backend/caregiver/repository/CaregiverRepositoryImpl.java
- src/main/java/com/patientpal/backend/patient/repository/PatientRepositoryImpl.java
- 지역 검색 시, 기존 eq()에서 like() + "%" 문으로 수정함.
> Fix: 지역 검색 시, 발생하는 에러 수정함

- src/main/java/com/patientpal/backend/config/WebSocketConfig.java
- src/main/java/com/patientpal/backend/post/controller/BoardController.java
- src/main/java/com/patientpal/backend/post/controller/NoticeController.java
- src/main/java/com/patientpal/backend/post/repository/PostRepository.java
- src/main/java/com/patientpal/backend/post/service/PostService.java
- 공지사항 get 요청시 자유게시판에서 동일 id 게시글을 가져오는 문제를 개선하였습니다.
- Closes #190
> Fix: 공지사항 get 요청 문제 개선

- src/main/java/com/patientpal/backend/chat/repository/ChatRepository.java
- src/main/java/com/patientpal/backend/chat/service/ChatService.java
> Fix: GetChats

- src/main/java/com/patientpal/backend/socket/subscriber/SocketSubscriber.java
- 메시지 수신시에도 socket publish가 되도록 수정했습니다.
> Fix: Socket publish

- src/main/java/com/patientpal/backend/matching/domain/MatchRepository.java
- src/main/java/com/patientpal/backend/matching/service/MatchServiceImpl.java
- src/main/java/com/patientpal/backend/matching/service/MatchStatusUpdateService.java
- 매칭 수락되고, 간병 기간 끝난 매칭상태 COMPLETED로 변경하는 스케쥴러 도입
- Closes # 197
> Feat: Batch MatchStatus COMPLETED

- src/main/java/com/patientpal/backend/caregiver/domain/Caregiver.java
- src/main/java/com/patientpal/backend/caregiver/dto/response/CaregiverProfileDetailResponse.java
- src/main/java/com/patientpal/backend/caregiver/service/CaregiverSearchService.java
- src/main/java/com/patientpal/backend/caregiver/service/CaregiverService.java
- src/main/java/com/patientpal/backend/matching/dto/response/CreateMatchResponse.java
- src/main/java/com/patientpal/backend/matching/dto/response/MatchResponse.java
- src/main/java/com/patientpal/backend/matching/service/MatchNotificationProxy.java
- src/main/java/com/patientpal/backend/member/domain/Member.java
- src/main/java/com/patientpal/backend/patient/dto/response/PatientProfileDetailResponse.java
- src/main/java/com/patientpal/backend/patient/repository/PatientRepositoryImpl.java
- src/main/java/com/patientpal/backend/patient/service/PatientSearchService.java
- src/main/java/com/patientpal/backend/patient/service/PatientService.java
- 간병인 검색 시 경력 조건 추가
- 매칭 신청 전 응답 값에 age 추가
- 환자, 간병인 프로필 세부 사항에 간병 희망 날짜 추가
- 캐싱 일시 제거
- Closes #206
> Feat: 간병인 검색 시 경력 추가, 프론트 요구사항 반영 2

- src/main/java/com/patientpal/backend/caregiver/domain/Caregiver.java
- src/main/java/com/patientpal/backend/member/domain/Member.java
- npe 방지 위해 Integer experienceYears -> int age 로 수정
> Fix: npe 방지 위해 Integer experienceYears -> int age 로 수정

- src/main/java/com/patientpal/backend/config/SecurityConfig.java
> Feat: add cors front prod

- src/main/java/com/patientpal/backend/caregiver/controller/CaregiverControllerV1.java
- src/main/java/com/patientpal/backend/caregiver/repository/CaregiverProfileSearchRepositoryCustom.java
- src/main/java/com/patientpal/backend/caregiver/repository/CaregiverRepositoryImpl.java
- src/main/java/com/patientpal/backend/caregiver/service/CaregiverSearchService.java
- src/main/java/com/patientpal/backend/patient/controller/PatientControllerV1.java
- src/main/java/com/patientpal/backend/patient/repository/PatientProfileSearchRepositoryCustom.java
- src/main/java/com/patientpal/backend/patient/repository/PatientRepositoryImpl.java
- src/main/java/com/patientpal/backend/patient/service/PatientSearchService.java
- src/main/java/com/patientpal/backend/review/domain/Reviews.java
- 프로필 검색 시 회원의 받은 리뷰수를 기준으로 정렬 기준 추가
> Feat: sort reviewCounts

- src/main/java/com/patientpal/backend/chat/controller/MessageController.java
- src/main/java/com/patientpal/backend/chat/dto/MessageRequestParam.java
- src/main/java/com/patientpal/backend/chat/repository/MessageRepository.java
- src/main/java/com/patientpal/backend/chat/service/MessageService.java
- messages 조회에 paging을 추가했습니다.
> Feat: Implements paging in Message

- src/main/resources/application.yml
- 운영 db server timezone asia/seoul로 수정
> Fix: 운영 db server timezone asia/seoul로 수정

- src/main/java/com/patientpal/backend/chat/service/MessageService.java
- src/main/java/com/patientpal/backend/socket/dto/SocketDirectMessage.java
- src/main/java/com/patientpal/backend/socket/publisher/SocketPublisher.java
- src/main/java/com/patientpal/backend/socket/subscriber/SocketSubscriber.java
- socket 메세지에 memberId, userName, name, profileImageUrl, createdAt을 추가했습니다.
- #215
> Feat: Add attributes in SocketDirectMessage

- src/main/java/com/patientpal/backend/chat/service/MessageService.java
- MessageService에 ChatRepostory를 추가했습니다.
> Fix: Add ChatRepository in MessageService

- src/main/java/com/patientpal/backend/auth/dto/SignUpRequest.java
- src/main/java/com/patientpal/backend/member/domain/Member.java
- src/main/java/com/patientpal/backend/member/service/MemberService.java
Feat: Change age data type to int
- 회원가입이 되게 수정했습니다.
- age 컬럼이 not null이길 바라는 의도 대로 Integer 타입에서 int 타입으로 변경했습니다. 
- Fixes https://github.com/PatientPaI/backend/issues/225#issue-2461567362
> Fix: Add age in request

- src/main/java/com/patientpal/backend/chat/dto/SocketDirectSubscribeMessage.java
- src/main/java/com/patientpal/backend/socket/subscriber/SocketSubscriber.java
> Feat: Add socket message attributes

- Dockerfile
> Fix: timezone to kst

- src/main/java/com/patientpal/backend/matching/controller/MatchController.java
- src/main/java/com/patientpal/backend/matching/service/MatchService.java
- src/main/java/com/patientpal/backend/matching/service/MatchServiceImpl.java
- src/main/java/com/patientpal/backend/matching/service/PdfService.java
- src/main/resources/application.yml
- sse 통신 시 dbcp over로 off osiv
- add default.batch.fetch.size 
- Closes #229
> Fix: sse 통신 시 dbcp over로 off osiv

- Dockerfile
- src/main/java/com/patientpal/backend/common/logger/LogAspect.java
> Fix: remove log healthcheck

- src/main/resources/application.yml
- add port for monitoring
레퍼런스
-
> Feat: add port for monitoring

- src/main/resources/application.yml
> Feat: connect monitoring server

- src/main/resources/application.yml
> Fix: fix server port

- src/main/resources/application.yml
> Fix: fix port original

- src/main/java/com/patientpal/backend/member/controller/MemberController.java
- src/main/java/com/patientpal/backend/member/dto/MemberDetailResponse.java
- src/main/java/com/patientpal/backend/member/repository/MemberRepository.java
- src/main/java/com/patientpal/backend/member/service/MemberService.java
-  getMembers API를 생성했습니다.
- Closes https://github.com/PatientPaI/backend/issues/239
> Feat: Add getMembers API in MemberController

- src/main/java/com/patientpal/backend/member/controller/MemberController.java
> Fix: Check-username

- src/main/java/com/patientpal/backend/member/dto/MemberDetailResponse.java
- getMembers응답에 member_id를 추가했습니다.
> Feat: Add memberId in response of getMembers

- src/main/java/com/patientpal/backend/config/WebSocketConfig.java
- WebsocketConfig 에 프론트 배포 사이트 CORS 허용하였습니다
> Feat: Add cors allowed url

- src/main/java/com/patientpal/backend/caregiver/repository/CaregiverRepository.java
- src/main/java/com/patientpal/backend/caregiver/service/CaregiverService.java
- src/main/java/com/patientpal/backend/common/logger/LogAspect.java
- src/main/java/com/patientpal/backend/matching/service/MatchServiceImpl.java
- src/main/java/com/patientpal/backend/matching/service/MatchValidation.java
- src/main/java/com/patientpal/backend/member/domain/Member.java
- src/main/java/com/patientpal/backend/patient/repository/PatientRepository.java
- src/main/java/com/patientpal/backend/recommend/AddressBasedRecommendStrategy.java
- src/main/java/com/patientpal/backend/recommend/RecommendService.java
- src/main/java/com/patientpal/backend/recommend/RecommendStrategy.java
- src/main/java/com/patientpal/backend/recommend/ReviewCountBasedRecommendStrategy.java
- src/main/java/com/patientpal/backend/recommend/ViewCountBasedRecommendStrategy.java
- src/main/resources/application.yml
- 디자인패턴-전략패턴 도입하여 맞춤 추천 알고리즘 손쉽게 변경 가능
- Member 엔티티 equals&hashcode 추가하여 id를 이용한 동일성 보장
- Closes #188
> Refactor: 전략 패턴 도입하여 유연성 증가

- src/main/java/com/patientpal/backend/caregiver/repository/CaregiverRepository.java
- src/main/java/com/patientpal/backend/patient/repository/PatientRepository.java
- src/main/java/com/patientpal/backend/recommend/AddressBasedRecommendStrategy.java
- 맞춤 추천 시 기준으로 변경함.
- Closes #245
> Fix: change recommend sort

- src/main/java/com/patientpal/backend/matching/domain/MatchRepository.java
- 받은 매칭 리스트, 보낸 매칭 리스트 정렬 조건 시간 asc에서 desc로 변경
> Fix: change get-matches sort time desc

- src/main/java/com/patientpal/backend/notification/dto/NotificationDto.java
- src/main/java/com/patientpal/backend/notification/service/NotificationService.java
- subscribe 이후 1분 지날 시 connection 끊김 해결
- 연결 지속 시간 1시간 지날 시 AsyncRequestTimeoutExeption 정상이지만, 로그 안나오게 해결
- sse name "sse" -> "message"로 변경
- 더미데이터 프론트에서의 원활한 파싱을 위한 JSON 형식으로 변경해서 응답.
- Closes #248 
- https://stackoverflow.com/questions/52029329/invasive-asyncrequesttimeoutexception-with-spring-boot-2
> Fix: SSE 관련 수정, 프론트 요구 반영

- build.gradle
- src/main/java/com/patientpal/backend/chat/domain/Message.java
- src/main/java/com/patientpal/backend/chat/dto/MessageCreateRequest.java
- src/main/java/com/patientpal/backend/chat/dto/MessageCreateResponse.java
- src/main/java/com/patientpal/backend/chat/repository/MessageRepository.java
- src/main/java/com/patientpal/backend/chat/service/MessageService.java
- src/main/java/com/patientpal/backend/socket/dto/SocketDirectMessage.java
- src/main/java/com/patientpal/backend/socket/subscriber/SocketSubscriber.java
- message Id의 타입을 UUID로 변경했습니다
- 소켓에서도 messageId를 받고 보내도록 설정했습니다.
> Feat: Add uuid message id

- src/main/java/com/patientpal/backend/notification/controller/NotificationController.java
> Fix: solve sse connection shut

- src/main/java/com/patientpal/backend/chat/dto/MessageCreateRequest.java
- src/main/java/com/patientpal/backend/chat/service/MessageService.java
- src/main/java/com/patientpal/backend/socket/dto/SocketDirectMessage.java
- src/main/java/com/patientpal/backend/socket/subscriber/SocketSubscriber.java
- 메시지 ID 가 UUID 로 변환되지 않는 문제를 수정했습니다.
- #262 
- #254
> Fix: String to UUID 변환 문제 수정

- src/main/java/com/patientpal/backend/caregiver/dto/response/CaregiverRankingResponse.java
- src/main/java/com/patientpal/backend/member/domain/Member.java
- src/main/java/com/patientpal/backend/review/controller/ReviewController.java
- src/main/java/com/patientpal/backend/review/domain/Reviews.java
- src/main/java/com/patientpal/backend/review/dto/CreateReviewRequest.java
- src/main/java/com/patientpal/backend/review/dto/UpdateReviewRequest.java
- src/main/java/com/patientpal/backend/review/repository/ReviewRepository.java
- src/main/java/com/patientpal/backend/review/service/ReviewService.java
- src/test/java/com/patientpal/backend/fixtures/review/ReviewsFixture.java
- src/test/java/com/patientpal/backend/review/controller/ReviewsControllerTest.java
- src/test/java/com/patientpal/backend/review/service/ReviewsServiceTest.java
- 생성 과 업데이트 dto 분리
- 리뷰 생성시 이미 리뷰가 있는지 와 매칭이 되어 있는지 검증
- 모든 리뷰 조회, 리뷰어, 리뷰받는 사람 조회 페이징 처리
- 맴버와 리뷰 양방향 설정
- 상위 간병인 조회 지역을 일부 지역만 입력해도 검색가능 하게 수정
- 
- 
-
> Fix 리뷰 페이징 처리 및 세세한 수정

- src/main/java/com/patientpal/backend/member/controller/MemberController.java
- 파라미터 memberIds를 Nullable하게 변경했습니다.
https://discord.com/channels/1240118633259335751/1253363666796019844/1281267229366685757
> Fix: Empty memberIds

- src/main/java/com/patientpal/backend/review/controller/ReviewController.java
- src/main/java/com/patientpal/backend/review/domain/Reviews.java
- Reviews에 BaseEntity 상속
- 페이징 정렬은 createdDate의 내림차순으로 함
- 
- 
-
> [Refactoring] 페이징 조회 리팩토링

- src/main/java/com/patientpal/backend/review/controller/ReviewController.java
- src/main/java/com/patientpal/backend/review/domain/Reviews.java
- db 마이그레이션이 안되므로 정렬 컬럼 제거
- 
- 
-
> [Refactoring] 리뷰 조회기능 정렬 제거 

- src/main/java/com/patientpal/backend/auth/controller/OAuth2LoginController.java
- src/main/java/com/patientpal/backend/member/service/MemberService.java
- src/main/java/com/patientpal/backend/security/oauth/dto/Oauth2SignUpRequest.java
- src/main/java/com/patientpal/backend/security/oauth/dto/Oauth2SignUpResponse.java
- src/main/resources/application-oauth2.yml
- src/test/java/com/patientpal/backend/auth/controller/OAuth2LoginControllerTest.java
- 로그인 요청 시 회원 가입 된 유저가 아니면 회원가입 페이지로 리다이렉트
- 추가 내용 받을 수 있게 수정
- 
- 
-
> [fix] 회원가입 기능 수정
